### ISSUE TITLE
ERROR:root:File `'Scripts/methods_generator.ipy.py'` not found.

### ISSUE THREAD

**Issue by veitveit** [ProtProtocols/IsoLabeledProtocol#62]
This happens when running the example and pressing the R script button

@jgriss Is there missing a file?

**Comment by jgriss** [comment]
@veitveit 

I just saw that the docker image building process failed after the last few commits. Unfortunately, I cannot access the build log since that's only possible through the respective user account. Could you have a look to see what went wrong? Simultaneously, I'm now rebuilding it on my side to see if something goes wrong here as well.

On a general note: We should add some kind of notification when the docker image building is failing.

**Comment by veitveit** [comment]
The Dockerfile was not updated to copy the right notebook file. It should work now (after the image is compiled)
